version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: mykv
    
    environment:
      - PYTHONUNBUFFERED=1

    ports:
      - "8083:8083"

    volumes:
      - ./data.txt:/app/data.txt:rw

    # user: "appuser"

    restart: unless-stopped

